name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add source
      run: dotnet nuget add source https://nuget.pkg.github.com/andrefmello91/index.json -n default -u andrefmello91 -p ${{secrets.NUGET_GITHUB_KEY}} --store-password-in-clear-text
    - name: Enable source
      run: dotnet nuget enable source default
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.5  
      with:   
       PROJECT_FILE_PATH: andrefmello91.OnPlaneComponents/andrefmello91.OnPlaneComponents.csproj  
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
    - name: PublishGitHub  
      uses: Rebel028/publish-nuget@2.6.1  
      with:   
       PROJECT_FILE_PATH: andrefmello91.OnPlaneComponents/andrefmello91.OnPlaneComponents.csproj
       NUGET_SOURCE: https://nuget.pkg.github.com/andrefmello91
       NUGET_KEY: ${{secrets.NUGET_GITHUB_KEY}}
